FROM mcr.microsoft.com/powershell:7.1.4-ubuntu-20.04

RUN apt-get update && \
    apt-get install -y apache2 curl supervisor vim tzdata &&\
    rm -rf /var/lib/apt/lists/*

RUN pwsh -c "Install-Module -Name VMware.PowerCLI -AllowClobber -Force"

ENV TZ="Asia/Taipei"

WORKDIR /workspace

COPY vm_info.ps1 /workspace

ENTRYPOINT ["pwsh"]
